# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: bash <(curl -s -L https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh) -apiKey a882a356-ba8e-45bf-a986-14dae877e437 -project chen -d ~/
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
